# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image with tests
      run: |
        DOCKER_BUILDKIT=1 docker build -t hairstyler-dev -f Dockerfile.dev .
    - name: Run Docker image with  tests
      run: |
        docker run hairstyler-tests
